name: drip
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ansicolor: ^2.0.1
  flutter:
    sdk: flutter
  logger: ^1.3.0
  meta: ^1.8.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
