name: drip
description: Minimalist chunked State Management for Flutter
version: 0.0.1
homepage: https://github.com/jamescardona11/drip

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
